import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {normalizePhone,validPhone,deliveryFields} from '../assets/js/dossier-profile.js';
const source=['live-original/Original.gs','LegacyUpgrade.gs','Accounts.gs','AdminAccounts.gs'].map(n=>fs.readFileSync(new URL('../backend/'+n,import.meta.url),'utf8')).join('\n');
function context(){
  const rows={PortalUnits:[{id:'UNIT-FACULTY1',name:'Khoa kiểm thử',type:'faculty',active:true}],UnitMembers:[],AdminAccounts:[],StudentProfiles:[],ApplicationExtras:[],PortalRequests:[],MailQueue:[],Hardcopies:[],AuditLog:[]},writes=[];
  const c=vm.createContext({console,Date,JSON,Map,Set,Number,Object,Error,Utilities:{getUuid:()=> 'test-uuid'},LockService:{getScriptLock:()=>({tryLock:()=>true,releaseLock(){}})},PropertiesService:{getScriptProperties:()=>({getProperty:()=> 'true'})}});vm.runInContext(source,c);
  c.portalV3Rows_=name=>rows[name];c.portalV3Append_=(name,data)=>({name,data});c.portalV3Update_=(name,data)=>({name,data});c.portalV3Batch_=requests=>writes.push(requests);c.portalV3Sheet_=()=>({});c.isAdmin_=()=>false;
  return {c,rows,writes};
}
const user={uid:'unit-uid',email:'khoa.test@units.huit-youth-portal.local',emailVerified:false,isAnonymous:false};
function member(rows){rows.UnitMembers.push({email:user.email,uid:user.uid,unitId:'UNIT-FACULTY1',active:true});}
test('Frontend and server agree on Vietnamese phones and postal requirements',()=>{const {c}=context();for(const [input,valid] of [['+84 912 345 678',true],['02812345678',true],['0291234567',false],['123',false],['0901234567',true]]){assert.equal(validPhone(input),valid);if(valid)assert.equal(c.portalV4Phone_(input,true),normalizePhone(input));else assert.throws(()=>c.portalV4Phone_(input,true));}assert.throws(()=>deliveryFields('post','0901234567','short'));assert.equal(deliveryFields('office','bad','old').deliveryAddress,'');assert.throws(()=>c.portalV4ApplicationInput_({deliveryMethod:'bad'},{},null));});
test('Synthetic email cannot grant unit access without exact active UID membership',()=>{const {c,rows}=context();assert.equal(c.portalV4Membership_(user),null);member(rows);assert.equal(c.portalV4Membership_(user).unitId,'UNIT-FACULTY1');assert.equal(c.portalV4Membership_({...user,uid:'attacker'}),null);rows.UnitMembers[0].active=false;assert.equal(c.portalV4Membership_(user),null);rows.UnitMembers[0].active=true;rows.PortalUnits[0].active=false;assert.equal(c.portalV4Membership_(user),null);});
test('Postal input preserves address and does not let a member submit as another unit',()=>{const {c,rows}=context();member(rows);const membership=c.portalV4Membership_(user);const value=c.portalV4ApplicationInput_({deliveryMethod:'post',deliveryPhone:'+84912345678',deliveryAddress:'123 đường Kiểm Thử\nPhường A, TP.HCM'},user,membership);assert.equal(value.deliveryPhone,'0912345678');assert.equal(value.unitId,'UNIT-FACULTY1');assert.throws(()=>c.portalV4ApplicationInput_({unitId:'UNIT-OTHER'},user,membership),e=>e.code==='UNIT_ACCESS_REQUIRED');assert.throws(()=>c.portalV4ApplicationInput_({deliveryMethod:'post',deliveryPhone:'0912345678'},user,membership));});
test('Unit dashboard isolates records and paginates all matching applications',()=>{const {c,rows}=context();member(rows);c.portalV3Applications_=()=>Array.from({length:25},(_,i)=>({id:'HS-'+i,unitId:'UNIT-FACULTY1',status:'Đang xử lý',submittedAt:new Date(2026,0,i+1).toISOString()})).concat([{id:'PRIVATE',unitId:'OTHER',status:'Hoàn thành'}]);const result=c.portalV4Dashboard_(user,{page:2,pageSize:20});assert.equal(result.summary.total,25);assert.equal(result.total,25);assert.equal(result.applications.length,5);assert.ok(result.applications.every(a=>a.unitId==='UNIT-FACULTY1'));assert.throws(()=>c.portalV4Dashboard_(user,{unitId:'OTHER'}),e=>e.code==='UNIT_ACCESS_REQUIRED');});
test('Disabled unit account cannot retrieve its old personal history',()=>{const {c}=context();c.authenticate_=()=>user;assert.throws(()=>c.portalV3ListMine_({}),e=>e.code==='UNIT_ACCESS_REQUIRED');});
test('Account creation persists UID membership but never password or auth token',()=>{const {c,writes}=context();const secret='not-a-real-password';c.portalV4FirebasePassword_=(method,email,password)=>{assert.equal(method,'signUp');assert.equal(password,secret);return {ok:true,data:{localId:'new-uid',email,idToken:'not-a-real-token'}};};const result=c.portalV4CreateAccount_({uid:'admin'},{username:'khoa.test',password:secret,unitId:'UNIT-FACULTY1',displayName:'Khoa kiểm thử'});assert.equal(result.account.uid,'new-uid');assert.equal(writes.length,1);assert.equal(writes[0][0].data.uid,'new-uid');assert.ok(!JSON.stringify(writes).includes(secret));assert.ok(!JSON.stringify(writes).includes('not-a-real-token'));});
test('Previously registered username requires matching password before attaching membership',()=>{const {c,writes}=context();let calls=[];c.portalV4FirebasePassword_=method=>{calls.push(method);return {ok:false,data:{error:{message:method==='signUp'?'EMAIL_EXISTS':'INVALID_PASSWORD'}}};};assert.throws(()=>c.portalV4CreateAccount_({uid:'admin'},{username:'khoa.test',password:'test-password',unitId:'UNIT-FACULTY1'}),e=>e.code==='ACCOUNT_EXISTS');assert.deepEqual(calls,['signUp','signInWithPassword']);assert.equal(writes.length,0);});
test('Unit submissions use server identity and atomically persist delivery without synthetic email reminders',()=>{const {c,rows,writes}=context();member(rows);c.authenticate_=()=>user;c.portalV3Applications_=()=>[];c.validateApplication_=raw=>raw;c.checkSubmissionRate_=()=>{};c.generateApplicationId_=()=> 'HS-TEST';c.getApplicationSheet_=()=>({});c.getLogSheet_=()=>({});c.portalV3AppendValues_=(sheet,data)=>({data});const result=c.portalV3Create_({requestId:'request-test',application:{studentName:'forged',studentId:'forged',studentEmail:'victim@example.com',docType:'Kế hoạch',reason:'Nội dung đề nghị',deliveryMethod:'post',deliveryPhone:'0912345678',deliveryAddress:'123 đường Kiểm Thử, Thành phố Hồ Chí Minh'}});assert.equal(result.application.studentName,'Khoa kiểm thử');assert.equal(result.application.studentId,'UNIT-FACULTY1');assert.equal(result.application.email,user.email);assert.equal(result.reminder,null);assert.equal(writes.length,1);const extra=writes[0].find(r=>r.name==='ApplicationExtras');assert.equal(extra.data.deliveryMethod,'post');assert.equal(extra.data.applicationId,'HS-TEST');assert.ok(!writes[0].some(r=>r.name==='MailQueue'));});
test('Account and unit management routes always require admin verification',()=>{const {c}=context();for(const action of ['createUnitAccountAdmin','saveUnitAdmin','saveUnitMemberAdmin','listUnitMembersAdmin','listUnitsAdmin']){c.authenticate_=(token,admin)=>{assert.equal(admin,true);throw Object.assign(new Error('denied'),{code:'ADMIN_REQUIRED'});};assert.throws(()=>c.portalV4Route_(action,{}),e=>e.code==='ADMIN_REQUIRED');}});
