import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import fs from 'node:fs';
const source=['Code.gs','Admin.gs','Mail.gs'].map(file=>fs.readFileSync(new URL('../backend/'+file,import.meta.url),'utf8')).join('\n');
function context(){const calls=[];const c=vm.createContext({console,Date,JSON,Object,Error,encodeURIComponent,PropertiesService:{getScriptProperties:()=>({getProperty:key=>({ADMIN_EMAILS:'admin@example.com',SPREADSHEET_ID:'test'})[key]})},LockService:{getScriptLock:()=>({tryLock:()=>true,releaseLock(){}})},Sheets:{Spreadsheets:{batchUpdate:(payload,id)=>calls.push({payload,id})}},Utilities:{getUuid:()=> 'operation-id'}});vm.runInContext(source,c);return {c,calls};}
test('Non-admin cannot access admin operations',()=>{const {c}=context();assert.throws(()=>c.requireAdmin_({email:'student@example.com'}),e=>e.code==='FORBIDDEN');assert.doesNotThrow(()=>c.requireAdmin_({email:'ADMIN@example.com'}));});
test('Concurrent status or note updates are rejected before any write',()=>{const {c,calls}=context();c.records_=()=>[{id:'HS-1',status:'Hoàn thành',updatedAt:'new'}];for(const payload of [{expectedStatus:'Đang xử lý'},{expectedStatus:'Hoàn thành',expectedUpdatedAt:'old'}])assert.throws(()=>c.updateApplication_({localId:'admin'},{applicationId:'HS-1',status:'Từ chối',...payload}),e=>e.code==='CONFLICT');assert.equal(calls.length,0);});
test('Status, audit and notification use one atomic batch and literal strings',()=>{const {c,calls}=context();c.records_=()=>[{id:'HS-1',uid:'student-1',status:'Đang xử lý',updatedAt:'old'}];c.sheet_=name=>({getSheetId:()=>({Applications:1,AuditLog:2,Notifications:3})[name]});c.updateApplication_({localId:'admin'},{applicationId:'HS-1',expectedStatus:'Đang xử lý',expectedUpdatedAt:'old',status:'Hoàn thành',note:'=HYPERLINK("malicious")'});assert.equal(calls.length,1);assert.equal(calls[0].payload.requests.length,3);const update=calls[0].payload.requests[0].updateCells;assert.equal(update.range.startRowIndex,1);assert.equal(update.rows[0].values[11].userEnteredValue.stringValue,'=HYPERLINK("malicious")');assert.equal(update.rows[0].values[11].userEnteredValue.formulaValue,undefined);});
test('Invalid inputs fail before database writes',()=>{const {c}=context();assert.throws(()=>c.updateApplication_({}, {applicationId:'x',status:'hacked'}),e=>e.code==='INVALID_INPUT');assert.throws(()=>c.createApplication_({localId:'x',email:'x@example.com'},{application:{docType:'x',studentName:'X',studentId:'12345',reason:'valid reason',studentEmail:'x@example.com'}}),e=>e.code==='INVALID_INPUT');});
test('Repeated request ID returns existing application without writing another',()=>{const {c}=context();c.records_=()=>[{id:'HS-existing',uid:'u',requestId:'request-123'}];const result=c.createApplication_({localId:'u',email:'u@example.com'},{requestId:'request-123',application:{docType:'Hồ sơ',studentName:'Nguyễn An',studentId:'2008220017',reason:'Nội dung hồ sơ đầy đủ',studentEmail:'u@example.com'}});assert.equal(result.application.id,'HS-existing');});
test('Plan submission commits the application and reminder in the same batch',()=>{const {c,calls}=context();c.records_=()=>[];c.sheet_=name=>({getSheetId:()=>({Applications:1,MailQueue:4})[name]});const result=c.createApplication_({localId:'u',email:'u@example.com'},{requestId:'request-plan',application:{docType:'Kế hoạch - Quyết định',studentName:'Nguyễn An',studentId:'2008220017',reason:'Nội dung hồ sơ đầy đủ',studentEmail:'u@example.com'}});assert.equal(calls.length,1);assert.deepEqual(Array.from(calls[0].payload.requests,r=>r.appendCells.sheetId),[1,4]);assert.equal(result.reminder.dueAt,c.nextMorning_(result.application.submittedAt));assert.equal(calls[0].payload.requests[1].appendCells.rows[0].values[2].userEnteredValue.stringValue,'u@example.com');});
test('Receiving hardcopy commits receipt, audit and pending email cancellation together',()=>{const {c,calls}=context();const records={Applications:[{id:'HS-1',docType:'Kế hoạch - Quyết định',status:'Đang xử lý'}],Hardcopies:[],MailQueue:[{id:'mail-1',applicationId:'HS-1',state:'pending'}]};c.records_=name=>records[name];c.sheet_=name=>({getSheetId:()=>({Hardcopies:5,AuditLog:2,MailQueue:4})[name]});c.recordHardcopy_({localId:'admin'},{applicationId:'HS-1'});assert.equal(calls.length,1);const requests=calls[0].payload.requests;assert.equal(requests.length,3);assert.equal(requests[2].updateCells.rows[0].values[5].userEnteredValue.stringValue,'cancelled');});
test('Manual email retry requires explicit confirmation and current uncertain state',()=>{const {c,calls}=context();assert.throws(()=>c.retryReminder_({localId:'admin'},{jobId:'mail-1'}),e=>e.code==='CONFIRM_REQUIRED');c.records_=()=>[{id:'mail-1',state:'sent'}];assert.throws(()=>c.retryReminder_({localId:'admin'},{jobId:'mail-1',confirmDuplicateRisk:true}),e=>e.code==='CONFLICT');assert.equal(calls.length,0);});
