import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import fs from 'node:fs';
const source=fs.readFileSync(new URL('../backend/deploy/Code.gs',import.meta.url),'utf8');
function context(){const c=vm.createContext({console:{error(){}},Date,JSON,Number,Object,Error,encodeURIComponent,ContentService:{MimeType:{JSON:'json'},createTextOutput:s=>({setMimeType:()=>JSON.parse(s)})}});vm.runInContext(source,c);return c;}
test('Deployment routes legacy and new administration through authenticated adapter',()=>{const c=context();let actions=[];c.portalV3Route_=(a,b)=>{actions.push(a);assert.equal(b.authToken,'test');return {};};for(const action of ['listApplications','listAdminApplications','updateApplicationStatus','updateApplication','recordHardcopy'])assert.equal(c.doPost({postData:{contents:JSON.stringify({action,authToken:'test'})}}).success,true);assert.equal(actions.length,5);});
test('Deployment refuses tokenless news writes; public GET cannot dispatch admin actions',()=>{const c=context();assert.equal(c.doPost({postData:{contents:JSON.stringify({action:'saveNews'})}}).code,'AUTH_REQUIRED');assert.equal(c.doGet({parameter:{action:'listNewsAdmin'}}).code,'UNKNOWN_ACTION');assert.equal(c.doGet({parameter:{}}).version,3);});
test('Strict original schema check never overwrites an existing header',()=>{const c=context();let writes=0;const sheet={getMaxColumns:()=>20,getRange:()=>({getValues:()=>[['Old header']],setValues:()=>writes++})};assert.throws(()=>c.ensureSheet_({getSheetByName:()=>sheet},'Hồ sơ',['Mã hồ sơ']),e=>e.code==='SCHEMA_MISMATCH');assert.equal(writes,0);});
test('Verified token belonging to another Firebase project is rejected',()=>{const c=context();c.requiredProperty_=()=> 'key';c.UrlFetchApp={fetch:()=>({getResponseCode:()=>200,getContentText:()=>JSON.stringify({users:[{localId:'u',emailVerified:true,email:'admin@example.com'}]})})};c.Utilities={base64DecodeWebSafe:()=>[],newBlob:()=>({getDataAsString:()=>JSON.stringify({aud:'another-project',iss:'https://securetoken.google.com/another-project',sub:'u',exp:Date.now()/1000+1000})})};assert.throws(()=>c.authenticate_('x'.repeat(120),true),e=>e.code==='AUTH_INVALID');});

test('Locked synthetic unit identity is denied before any protected route',()=>{const c=context();c.requiredProperty_=()=> 'key';c.UrlFetchApp={fetch:()=>({getResponseCode:()=>200,getContentText:()=>JSON.stringify({users:[{localId:'u',email:'unit@units.huit-youth-portal.local'}]})})};c.Utilities={base64DecodeWebSafe:()=>[],newBlob:()=>({getDataAsString:()=>JSON.stringify({aud:'huit-youth-portal',iss:'https://securetoken.google.com/huit-youth-portal',sub:'u',exp:Date.now()/1000+1000})})};c.portalV4Membership_=()=>null;assert.throws(()=>c.authenticate_('x'.repeat(120),false),e=>e.code==='UNIT_ACCESS_REQUIRED');});
