import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import fs from 'node:fs';
const source=['live-original/Original.gs','LegacyUpgrade.gs'].map(n=>fs.readFileSync(new URL('../backend/'+n,import.meta.url),'utf8')).join('\n');
function context(){const writes=[],rows={PortalRequests:[],MailQueue:[],Hardcopies:[],AuditLog:[]};let sendCount=0;const c=vm.createContext({console,Date,JSON,Map,Set,Number,Object,Error,encodeURIComponent,PropertiesService:{getScriptProperties:()=>({getProperty:()=> 'true'})},LockService:{getScriptLock:()=>({tryLock:()=>true,releaseLock(){}})},Utilities:{getUuid:()=> 'test-uuid',formatDate:d=>new Date(d.getTime()+7*3600000).toISOString().slice(0,10)},MailApp:{getRemainingDailyQuota:()=>100,sendEmail:()=>{sendCount++;}}});vm.runInContext(source,c);c.portalV3Rows_=name=>rows[name];c.portalV3Sheet_=name=>({getSheetId:()=>({PortalRequests:2,MailQueue:3,Hardcopies:4,AuditLog:5})[name]});c.portalV3Batch_=requests=>writes.push(requests);c.getApplicationSheet_=()=>({getSheetId:()=>1});c.getNotificationSheet_=()=>({getSheetId:()=>6});c.getLogSheet_=()=>({getSheetId:()=>7});c.authenticate_=()=>({uid:'admin',email:'admin@example.com',emailVerified:true});return {c,rows,writes,get sendCount(){return sendCount;}};}
test('Legacy mapping retains original email/file ID and physical row through gaps',()=>{const {c}=context();const row=['HS-1','uid','Nguyễn An','12345','a@example.com','Kế hoạch','Nội dung','test.pdf','file-id','https://drive.google.com/file/d/file-id','Đang xử lý','2026-09-19T01:00:00Z','2026-09-19T01:00:00Z','','','',0];c.readRows_=()=>[[],row];const apps=c.portalV3Applications_();assert.equal(apps.length,1);assert.equal(apps[0]._row,2);assert.equal(apps[0].fileId,'file-id');assert.equal(apps[0].email,'a@example.com');});
test('Legacy lists handle blank timestamps and filter Vietnam dates',()=>{const {c}=context();c.portalV3Applications_=()=>[{id:'bad',submittedAt:'',docType:'Kế hoạch',status:'Đang xử lý'},{id:'ok',submittedAt:'2026-09-19T17:00:00Z',docType:'Kế hoạch',status:'Đang xử lý'}];assert.equal(c.portalV3ListAdmin_({}).total,2);assert.equal(c.portalV3ListAdmin_({from:'2026-09-20',to:'2026-09-20'}).total,1);});
test('Legacy next morning is Vietnam calendar day including midnight rollover',()=>{const {c}=context();assert.equal(c.portalV3NextMorning_('2026-09-19T16:59:59Z'),'2026-09-20T01:00:00.000Z');assert.equal(c.portalV3NextMorning_('2026-09-19T17:00:00Z'),'2026-09-21T01:00:00.000Z');});
test('Legacy stale concurrent edit produces no database writes or mail',()=>{const {c,writes}=context();c.portalV3Applications_=()=>[{id:'HS-1',status:'Hoàn thành',updatedAt:'new'}];assert.throws(()=>c.portalV3Status_({}, {applicationId:'HS-1',status:'Đang xử lý',expectedStatus:'Đang xử lý',expectedUpdatedAt:'old'},true),e=>e.code==='CONFLICT');assert.equal(writes.length,0);});
test('Legacy status writes only processing columns plus audit, preserving files and identities',()=>{const {c,rows,writes}=context();c.portalV3Applications_=()=>[{id:'HS-1',uid:'u',studentEmail:'u@example.com',status:'Đang xử lý',updatedAt:'old',_row:5,updateCount:2}];rows.MailQueue.push({id:'job',applicationId:'HS-1',state:'pending',_row:1});c.portalV3Status_({uid:'admin',email:'admin@example.com'},{applicationId:'HS-1',status:'Từ chối',expectedStatus:'Đang xử lý',expectedUpdatedAt:'old'},true);assert.equal(writes.length,1);const updates=writes[0].filter(r=>r.updateCells?.range.sheetId===1);assert.deepEqual(Array.from(updates,r=>r.updateCells.range.startColumnIndex),[10,12,16]);assert.ok(updates.every(r=>r.updateCells.range.startRowIndex===5));assert.equal(writes[0].at(-1).updateCells.rows[0].values[5].userEnteredValue.stringValue,'cancelled');});
test('Reminder worker caps cancellation/error writes as well as sends',()=>{const {c,rows}=context();c.portalV3Applications_=()=>[];for(let i=0;i<45;i++)rows.MailQueue.push({id:'job-'+i,applicationId:'missing',state:'pending',dueAt:'2020-01-01T00:00:00Z'});let saves=0;c.portalV3SaveJob_=()=>saves++;c.portalV3ProcessReminderQueue();assert.equal(saves,20);});
test('Committed request retry includes persisted reminder metadata',()=>{const {c,rows,writes}=context();rows.PortalRequests.push({id:'request-123',uid:'admin',applicationId:'HS-1'});rows.MailQueue.push({applicationId:'HS-1',dueAt:'2026-09-20T01:00:00Z',state:'pending'});c.portalV3Applications_=()=>[{id:'HS-1',uid:'admin'}];c.validateApplication_=()=>({});const result=c.portalV3Create_({requestId:'request-123'});assert.equal(result.reminder.dueAt,'2026-09-20T01:00:00Z');assert.equal(writes.length,0);});
