import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import fs from 'node:fs';
import {validateNewsPost,isNewsImageDataUrl,newsParagraphs,newsFingerprint,requestIdentity} from '../assets/js/news-utils.js';
const valid={id:'NEWS-testing-1234',title:'Bài viết dùng kiểm tra',summary:'Mô tả ngắn đủ dài cho bài viết thử nghiệm.',content:'Nội dung dài hơn năm mươi ký tự để kiểm tra việc đăng bài được xác thực hợp lệ.',category:'Sự kiện',imageAlt:'Ảnh buổi sinh hoạt',status:'published'};
const original=fs.readFileSync(new URL('../backend/live-original/Original.gs',import.meta.url),'utf8'),news=fs.readFileSync(new URL('../backend/News.gs',import.meta.url),'utf8');
function context(){const writes=[],rows=[];const c=vm.createContext({console,Date,JSON,Map,Set,Number,Object,Error,encodeURIComponent,LockService:{getScriptLock:()=>({waitLock(){},releaseLock(){}})},Utilities:{getUuid:()=> 'unique-id'},ScriptApp:{getOAuthToken:()=> 'test'},UrlFetchApp:{fetch:(url,options)=>{writes.push(JSON.parse(options.payload));return {getResponseCode:()=>200};}}});vm.runInContext(original+'\n'+news,c);c.requiredProperty_=()=> 'test';c.newsRows_=()=>rows;c.newsSheet_=()=>({getSheetId:()=>7});c.authenticate_=()=>({uid:'admin',displayName:'Ban biên tập',emailVerified:true});return {c,writes,rows};}
test('Publication needs meaningful fields and cover; draft can be incomplete',()=>{assert.deepEqual(validateNewsPost(valid,{hasImage:true}),{});assert.ok(validateNewsPost(valid).image);assert.deepEqual(validateNewsPost({...valid,status:'draft',summary:'',content:'',imageAlt:''}),{});assert.ok(validateNewsPost({...valid,title:'x'},{hasImage:true}).title);});
test('Only raster data URLs are accepted; text paragraphs retain literal markup',()=>{assert.equal(isNewsImageDataUrl('data:image/svg+xml;base64,AAAA'),false);assert.equal(isNewsImageDataUrl('javascript:alert(1)'),false);assert.equal(isNewsImageDataUrl('data:image/jpeg;base64,/9j/'),true);assert.deepEqual(newsParagraphs('<script>x</script>\n\nSecond'),['<script>x</script>','Second']);});
test('Retry identity remains stable until article or image changes',()=>{let i=0;const fingerprint=newsFingerprint(valid,null,false),first=requestIdentity(null,fingerprint,()=>String(++i));assert.equal(requestIdentity(first,fingerprint,()=>String(++i)),first);assert.notEqual(requestIdentity(first,newsFingerprint({...valid,title:'Changed'},null,false),()=>String(++i)).requestId,first.requestId);});
test('Public news returns only published fields and denies draft images/detail',()=>{const {c,rows}=context();rows.push({...valid,status:'draft',imageFileId:'private-draft'},{...valid,id:'NEWS-public',status:'published',imageFileId:'private-cover',imageMime:'image/jpeg',authorUid:'private-uid',authorName:'Đoàn - Hội',revision:2,publishedAt:'2026-09-20T01:00:00Z'});const list=c.newsPublicRoute_('listPublicNews',{});assert.equal(list.posts.length,1);assert.equal(list.posts[0].imageFileId,undefined);assert.equal(list.posts[0].authorUid,undefined);assert.equal(list.posts[0].content,undefined);assert.throws(()=>c.newsPublicRoute_('getNewsImage',{id:valid.id}),e=>e.code==='NOT_FOUND');assert.throws(()=>c.newsPublicRoute_('getPublicNews',{id:valid.id}),e=>e.code==='NOT_FOUND');});
test('News save rejects stale revision before writing and repeats are idempotent',()=>{const {c,rows,writes}=context();rows.push({...valid,revision:2,lastRequestId:'previous',imageFileId:'cover',row:2});const body={post:{...valid},expectedRevision:1,requestId:'request-12345'};assert.throws(()=>c.newsSave_({uid:'admin'},body),e=>e.code==='CONFLICT');assert.equal(writes.length,0);rows[0].lastRequestId='request-12345';assert.equal(c.newsSave_({uid:'admin'},body).post.revision,2);assert.equal(writes.length,0);});
test('News draft writes one literal row and publication without cover is rejected',()=>{const {c,writes}=context();const post={...valid,status:'draft',title:'=HYPERLINK("literal")'};c.newsSave_({uid:'admin'},{post,expectedRevision:0,requestId:'request-12345'});assert.equal(writes.length,1);assert.equal(writes[0].requests[0].appendCells.rows[0].values[1].userEnteredValue.stringValue,post.title);assert.throws(()=>c.newsSave_({uid:'admin'},{post:valid,expectedRevision:0,requestId:'request-54321'}),e=>e.code==='IMAGE_REQUIRED');});
test('News mutation checks server admin permission',()=>{const {c,writes}=context();c.authenticate_=()=>{throw Object.assign(new Error('forbidden'),{code:'ADMIN_REQUIRED'});};assert.throws(()=>c.newsAdminRoute_('saveNews',{post:valid}),e=>e.code==='ADMIN_REQUIRED');assert.equal(writes.length,0);});

test('Public list cache is short and excludes private detail; unpublishing still denies article immediately',()=>{const {c,rows}=context();const cache=new Map();let ttl; c.CacheService={getScriptCache:()=>({get:k=>cache.get(k),put:(k,v,t)=>{cache.set(k,v);ttl=t;},remove:k=>cache.delete(k)})};rows.push({...valid,status:'published',authorUid:'private',imageFileId:'private-file',revision:1});const list=c.newsPublicRoute_('listPublicNews',{});assert.equal(ttl,15);assert.equal(list.posts.length,1);assert.ok(![...cache.values()][0].includes('private'));rows[0].status='draft';assert.throws(()=>c.newsPublicRoute_('getPublicNews',{id:valid.id}),e=>e.code==='NOT_FOUND');assert.throws(()=>c.newsPublicRoute_('getNewsImage',{id:valid.id}),e=>e.code==='NOT_FOUND');});

test('Saving an article invalidates the public list cache',()=>{const {c}=context();let removed=0;c.CacheService={getScriptCache:()=>({remove:()=>removed++})};c.newsSave_({uid:'admin'},{post:{...valid,status:'draft'},expectedRevision:0,requestId:'request-test'});assert.equal(removed,2);});
