import {validateNewsPost,NEWS_STATUSES,newsDate,newsDisplayTitle,renderNewsParagraphs,optimizeNewsImage,isNewsImageDataUrl,newsFingerprint,requestIdentity} from '../assets/js/news-utils.js';
import {readLocal,writeLocal} from '../assets/js/portal-utils.js';
export function mountEditor({request,logout}) {
  const $=id=>document.getElementById(id),fields=['title','summary','content','category','imageAlt'];
  const state={epoch:0,ready:false,busy:false,dirty:false,page:1,load:0,detail:0,current:null,image:null,removeImage:false,imageUrl:'',uid:'',pending:null,imageEpoch:0};let draftTimer,confirmResolve;
  const text=(tag,value,cls)=>{const e=document.createElement(tag);e.textContent=value;if(cls)e.className=cls;return e;};
  const form=$('postForm');
  function message(value,error=false){$('formError').hidden=!error;$('formError').textContent=error?value:'';$('saveState').textContent=value;}
  function markBusy(busy){state.busy=busy;$('postFields').disabled=busy||!state.ready;$('newPost').disabled=busy||!state.ready;$('previewPost').disabled=busy||!state.ready;}
  function current(status){return {id:state.current.id,title:form.elements.title.value.trim(),summary:form.elements.summary.value.trim(),content:form.elements.content.value.trim(),category:form.elements.category.value,imageAlt:form.elements.imageAlt.value.trim(),status};}
  const draftKey=()=>`huit:news-draft:${state.uid}`;
  function saveLocal(){if(!state.uid||!state.current)return;writeLocal(draftKey(),{post:current(state.current.status),revision:state.current.revision||0,savedAt:new Date().toISOString()});}
  function changed(){state.dirty=true;message('Có thay đổi chưa lưu lên hệ thống.');clearTimeout(draftTimer);draftTimer=setTimeout(saveLocal,500);$('wordCount').textContent=form.elements.content.value.trim().split(/\s+/).filter(Boolean).length+' từ';}
  function showImage(){const valid=isNewsImageDataUrl(state.imageUrl);$('coverPreview').hidden=!valid;$('coverPlaceholder').hidden=valid;$('removeImage').hidden=!valid&&!state.current?.hasImage;if(valid)$('coverPreview').src=state.imageUrl;else $('coverPreview').removeAttribute('src');}
  function setPost(post,dataUrl=''){
    clearTimeout(draftTimer);state.current={...post};state.image=null;state.removeImage=false;state.imageUrl=isNewsImageDataUrl(dataUrl)?dataUrl:'';state.pending=null;state.dirty=false;state.imageEpoch++;
    fields.forEach(key=>form.elements[key].value=post[key]||'');$('coverFile').value='';$('imageStatus').textContent='';$('postState').textContent=NEWS_STATUSES[post.status]||'Bản nháp';$('postState').className='post-badge '+post.status;$('writingTitle').textContent=post.revision?'Biên tập bài viết':'Viết một bài mới';$('archivePost').hidden=post.status!=='published';$('saveDraft').hidden=post.status==='published';$('publishPost').textContent=post.status==='published'?'Lưu thay đổi bài đã đăng':'Đăng lên trang chủ ↗';$('publicLink').hidden=post.status!=='published';$('publicLink').href='../tin-tuc/?id='+encodeURIComponent(post.id);$('wordCount').textContent=(post.content||'').trim().split(/\s+/).filter(Boolean).length+' từ';showImage();message(post.revision?'Đã tải phiên bản '+post.revision+' từ hệ thống.':'Bản nháp chỉ được đăng khi bạn chọn Đăng lên trang chủ.');
  }
  function newPost(){setPost({id:'NEWS-'+crypto.randomUUID(),title:'',summary:'',content:'',category:'Hoạt động Đoàn - Hội',imageAlt:'',status:'draft',revision:0,hasImage:false});}
  function confirm(title,copy){return new Promise(resolve=>{if(confirmResolve)confirmResolve(false);$('confirmTitle').textContent=title;$('confirmText').textContent=copy;confirmResolve=value=>{confirmResolve=null;$('confirmDialog').close();resolve(value);};$('confirmDialog').showModal();$('cancelConfirm').focus();});}
  $('cancelConfirm').onclick=()=>confirmResolve?.(false);$('acceptConfirm').onclick=()=>confirmResolve?.(true);$('confirmDialog').oncancel=e=>{e.preventDefault();confirmResolve?.(false);};
  async function canLeave(){return !state.dirty||await confirm('Bỏ thay đổi đang nhập?','Nội dung chưa lưu lên hệ thống. Tiếp tục sẽ rời bài đang soạn; bản nháp văn bản gần nhất vẫn được giữ trên thiết bị.');}
  async function loadList(){if(!state.ready)return;const epoch=state.epoch,load=++state.load;$('postList').replaceChildren(text('p','Đang tải danh sách…'));
    try{const result=await request('listNewsAdmin',{page:state.page,query:$('listQuery').value.trim(),status:$('listStatus').value});if(epoch!==state.epoch||load!==state.load)return;if(!Array.isArray(result.posts)||!result.summary)throw new Error('Dữ liệu danh sách không hợp lệ.');
      $('postSummary').textContent=`${result.summary.total} bài · ${result.summary.published} đã đăng · ${result.summary.draft} bản nháp`;$('postList').replaceChildren(...result.posts.map(post=>{const b=text('button','','post-item'+(post.id===state.current?.id?' active':''));b.type='button';const title=text('strong',newsDisplayTitle(post.title,{max:76}));title.title=post.title;b.append(text('span',NEWS_STATUSES[post.status],'post-badge '+post.status),title,text('small',post.category+' · '+newsDate(post.updatedAt)));b.onclick=()=>openPost(post.id);return b;}));if(!result.posts.length)$('postList').append(text('p','Chưa có bài phù hợp. Bấm Viết bài để bắt đầu.'));$('listPage').textContent='Trang '+result.page;$('prevPosts').disabled=result.page<=1;$('nextPosts').disabled=!result.hasMore;
    }catch(error){if(epoch===state.epoch){$('postList').replaceChildren(text('p',error.message));$('connectionState').textContent='Chưa tải được danh sách; bấm Tìm để thử lại.';}}
  }
  async function openPost(id){const epoch=state.epoch;if(state.busy||!await canLeave()||epoch!==state.epoch)return;const detail=++state.detail;markBusy(true);message('Đang mở bài viết…');try{const result=await request('getNewsAdmin',{id});if(epoch!==state.epoch||detail!==state.detail)return;setPost(result.post,result.dataUrl);await loadList();}catch(error){if(epoch===state.epoch)message(error.message,true);}finally{if(epoch===state.epoch)markBusy(false);}}
  async function save(status){if(state.busy||!state.ready)return;const post=current(status),errors=validateNewsPost(post,{hasImage:Boolean(state.image)||(!state.removeImage&&state.current.hasImage)});if(Object.keys(errors).length){message(Object.values(errors).join('\n'),true);return;}
    const epoch=state.epoch;if(status==='published'&&state.current.status!=='published'&&!await confirm('Đăng bài lên cổng thông tin?','Tiêu đề, nội dung và ảnh của bài viết sẽ hiển thị công khai ở mục tin tức trang chủ.'))return;if(status==='archived'&&!await confirm('Ẩn bài khỏi tin tức?','Bài viết sẽ không còn hiển thị công khai. Bạn vẫn có thể chỉnh sửa và đăng lại.'))return;if(epoch!==state.epoch)return;
    const image=state.image?{name:state.image.name,mimeType:state.image.mimeType,base64:state.image.base64}:null;
    state.pending=requestIdentity(state.pending,newsFingerprint(post,image,state.removeImage),()=>crypto.randomUUID());markBusy(true);message('Đang lưu bài viết và ảnh lên hệ thống…');saveLocal();
    try{const result=await request('saveNews',{post,expectedRevision:state.current.revision||0,requestId:state.pending.requestId,...(image?{image}:{}),removeImage:state.removeImage});if(epoch!==state.epoch)return;if(!result.post?.id)throw new Error('Máy chủ chưa xác nhận bài viết. Hãy thử lưu lại cùng nội dung.');const preview=state.imageUrl;setPost(result.post,preview);try{localStorage.removeItem(draftKey());}catch{}$('draftOffer').hidden=true;message(status==='published'?'Đã đăng thành công. Bài viết tự xuất hiện ở tin tức trang chủ.':status==='archived'?'Đã ẩn bài khỏi trang tin tức.':'Đã lưu bản nháp lên hệ thống.');await loadList();
    }catch(error){if(epoch===state.epoch)message(error.message+' Nội dung đang soạn vẫn được giữ lại.',true);}finally{if(epoch===state.epoch)markBusy(false);}
  }
  form.onsubmit=e=>{e.preventDefault();save('published');};form.oninput=changed;$('saveDraft').onclick=()=>save('draft');$('archivePost').onclick=()=>save('archived');
  $('coverFile').onchange=async()=>{const file=$('coverFile').files[0];if(!file)return;const epoch=state.epoch,imageEpoch=++state.imageEpoch;markBusy(true);$('imageStatus').textContent='Đang tối ưu ảnh…';try{const image=await optimizeNewsImage(file);if(epoch!==state.epoch||imageEpoch!==state.imageEpoch)return;state.image=image;state.imageUrl=image.dataUrl;state.removeImage=false;$('imageStatus').textContent=`${image.width} × ${image.height} · ${Math.ceil(image.bytes/1024)} KB · sẵn sàng tải lên`;showImage();changed();}catch(error){if(epoch===state.epoch){$('imageStatus').textContent=error.message;$('coverFile').value='';}}finally{if(epoch===state.epoch)markBusy(false);}};
  $('removeImage').onclick=()=>{state.image=null;state.imageUrl='';state.removeImage=true;$('coverFile').value='';showImage();changed();};
  $('previewPost').onclick=()=>{const p=current('draft');$('previewTitle').textContent=newsDisplayTitle(p.title,{max:112})||'Tiêu đề bài viết';$('previewTitle').title=p.title;$('previewSummary').textContent=p.summary;$('previewCategory').textContent=p.category;renderNewsParagraphs($('previewContent'),p.content);$('previewImage').hidden=!isNewsImageDataUrl(state.imageUrl);if(state.imageUrl)$('previewImage').src=state.imageUrl;$('previewImage').alt=p.imageAlt;$('previewDialog').showModal();};$('closePreview').onclick=()=>$('previewDialog').close();
  $('newPost').onclick=async()=>{const epoch=state.epoch;if(!state.busy&&await canLeave()&&epoch===state.epoch){newPost();form.elements.title.focus();}};
  $('listFilters').onsubmit=e=>{e.preventDefault();state.page=1;loadList();};$('prevPosts').onclick=()=>{state.page--;loadList();};$('nextPosts').onclick=()=>{state.page++;loadList();};
  $('restoreDraft').onclick=async()=>{const saved=readLocal(draftKey(),null);if(!saved?.post||state.busy)return;const epoch=state.epoch;markBusy(true);try{let base=null;if(saved.revision){base=await request('getNewsAdmin',{id:saved.post.id});if(Number(base.post.revision)!==Number(saved.revision))throw new Error('Bài trên máy chủ đã thay đổi. Hãy mở bài đó để đối chiếu trước khi khôi phục bản lưu trên thiết bị.');}if(epoch!==state.epoch)return;setPost({...saved.post,revision:saved.revision,hasImage:Boolean(base?.post.hasImage)},base?.dataUrl||'');state.dirty=true;message('Đã khôi phục văn bản. Ảnh chưa tải lên trước đó cần chọn lại.');$('draftOffer').hidden=true;}catch(error){if(epoch===state.epoch)message(error.message,true);}finally{if(epoch===state.epoch)markBusy(false);}};
  $('discardDraft').onclick=()=>{try{localStorage.removeItem(draftKey());$('draftOffer').hidden=true;}catch{message('Không thể xóa bản lưu trên thiết bị.',true);}};
  $('logout').onclick=async()=>{if(state.busy||!await canLeave())return;try{await logout();}catch{message('Chưa đăng xuất được. Vui lòng thử lại.',true);}};
  window.addEventListener('beforeunload',e=>{if(state.dirty){saveLocal();e.preventDefault();e.returnValue='';}});
  async function connect(name,uid){const epoch=++state.epoch;state.uid=uid;state.ready=false;$('editorName').textContent=name;$('connectionError').hidden=true;$('reconnect').hidden=true;markBusy(true);try{const result=await request('verifyAdmin');if(epoch!==state.epoch)return;if(result.capabilities?.news?.version!==1)throw new Error('Máy chủ chưa bật quản lý bài viết. Cần cập nhật phiên bản Apps Script và khởi tạo kho bài viết.');state.ready=true;newPost();$('connectionState').textContent='Đã xác thực quyền biên tập';$('draftOffer').hidden=!readLocal(draftKey(),null);await loadList();}catch(error){if(epoch===state.epoch){$('connectionError').textContent=error.message;$('connectionError').hidden=false;$('reconnect').hidden=false;$('postList').replaceChildren(text('p','Chưa kết nối được kho bài viết.'));}}finally{if(epoch===state.epoch)markBusy(false);}}
  $('reconnect').onclick=()=>connect($('editorName').textContent,state.uid);
  function clear(){state.epoch++;state.detail++;state.imageEpoch++;state.ready=false;state.dirty=false;state.current=null;state.image=null;state.imageUrl='';state.uid='';clearTimeout(draftTimer);confirmResolve?.(false);$('previewDialog').close();['previewTitle','previewSummary','previewCategory','previewContent'].forEach(id=>$(id).replaceChildren());$('previewImage').removeAttribute('src');form.reset();$('postList').replaceChildren();$('coverPreview').removeAttribute('src');$('coverPreview').hidden=true;$('draftOffer').hidden=true;markBusy(false);}
  return {connect,clear};
}
