import {publicNewsRequest,loadNewsImage} from '../assets/js/news-api.js';
import {newsDate,newsDisplayTitle,renderNewsParagraphs} from '../assets/js/news-utils.js';
import {createNewsCard,disposeNewsCards} from '../assets/js/news-cards.js';
const $=id=>document.getElementById(id),id=new URLSearchParams(location.search).get('id');let page=1,generation=0;
async function load(){const gen=++generation;$('newsStatus').hidden=false;$('newsStatus').textContent='Đang tải tin tức…';$('retryNews').hidden=true;$('previousNews').disabled=true;$('nextNews').disabled=true;
  try{
    if(id){$('newsListing').hidden=true;const {post}=await publicNewsRequest('getPublicNews',{id});if(gen!==generation)return;if(!post?.id)throw new Error('Chưa tìm thấy bài viết này.');const displayTitle=newsDisplayTitle(post.title,{max:112});$('articleTitle').textContent=displayTitle;$('articleTitle').title=post.title;$('articleTitle').setAttribute('aria-label',post.title);document.title=post.title+' · HUIT';$('articleCategory').textContent=post.category;$('articleAuthor').textContent=post.authorName;$('articleDate').textContent=newsDate(post.publishedAt);$('articleDate').dateTime=post.publishedAt;$('articleSummary').textContent=post.summary;renderNewsParagraphs($('articleBody'),post.content);$('newsArticle').hidden=false;$('newsStatus').hidden=true;if(post.hasImage){try{const src=await loadNewsImage(id,{revision:post.revision});if(gen!==generation)return;$('articleImage').src=src;$('articleImage').alt=post.imageAlt;$('articleCaption').textContent=post.imageAlt;$('articleFigure').hidden=false;}catch{$('newsStatus').textContent='Nội dung đã tải. Ảnh bìa chưa tải được; bạn có thể thử lại.';$('newsStatus').hidden=false;$('retryNews').hidden=false;}}
    }else{const result=await publicNewsRequest('listPublicNews',{page,query:$('newsQuery').value.trim(),category:$('newsCategory').value});if(gen!==generation)return;if(!Array.isArray(result.posts))throw new Error('Máy chủ chưa hỗ trợ kho tin tức.');disposeNewsCards($('publicNewsGrid'));$('publicNewsGrid').replaceChildren(...result.posts.map(post=>createNewsCard(post)));$('newsStatus').textContent=result.posts.length?'':'Chưa có bài viết phù hợp. Các tin trước đây vẫn có tại trang chủ.';$('newsStatus').hidden=result.posts.length>0;$('newsPageNumber').textContent=`Trang ${page} · ${result.total} bài`;$('previousNews').disabled=page<=1;$('nextNews').disabled=!result.hasMore;}
  }catch(error){if(gen===generation){$('newsStatus').textContent=error.message;$('newsStatus').hidden=false;$('retryNews').hidden=false;}}
}
$('newsFilters').onsubmit=e=>{e.preventDefault();page=1;load();};$('previousNews').onclick=()=>{page--;load();};$('nextNews').onclick=()=>{page++;load();};$('retryNews').onclick=load;$('shareArticle').onclick=async()=>{try{await navigator.clipboard.writeText(location.href);$('shareStatus').textContent='Đã sao chép liên kết.';}catch{$('shareStatus').textContent='Bạn có thể sao chép địa chỉ trên thanh trình duyệt.';}};load();
